
/**
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 */


#include <string>
class Solution {
public:
    char findTheDifference(std::string s, std::string t) {
        unsigned int sum1 = 0;
        unsigned int sum2 = 0;
        for (int i = 0; i < s.length(); i++)
        {
            sum1 += s[i];
            sum2 += t[i];
        }
        sum2 += t[t.length() - 1];
        return (char)(sum2 - sum1);
    }
};

/**
Intuition:
Using property of character - can be represented as integer.

Approach:
We know that string t is made up of all the same characters that s is made of, with the addition of 1 extra character.

Since characters can be represented as integers, we can use that property to calculate sum of all values for both lists, and then substracting sum of list s from the sum of list t. That will give us integer that represents character that has been added.

Doesn't matter if string contains both upper and lower case because s.length() characters will be same in both lists, and only 1 will differ (that is the additional one). This means that sum of all values from list s will cancel sum of t.length() - 1 elements in list t, leaving only added character, which is our solution.

Complexity:
Time complexity:
O(n)

Space complexity:
O(1)
*/
